-- MySQL Script generated by MySQL Workbench
-- 10/18/17 01:52:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moviedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviedb` DEFAULT CHARACTER SET utf8 ;
USE `moviedb` ;

-- -----------------------------------------------------
-- Table `moviedb`.`mesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`mesto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ryad` INT(11) NULL DEFAULT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `cost` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviedb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `persontype` VARCHAR(45) NULL DEFAULT NULL,
  `cash` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviedb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`film` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cost` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `info` VARCHAR(500) NULL DEFAULT NULL,
  `filmstatus` VARCHAR(45) NULL DEFAULT NULL,
  `kinkompid` INT(11) NULL DEFAULT NULL,
  `time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_to_person_idx` (`kinkompid` ASC),
  CONSTRAINT `fk_film_to_person`
    FOREIGN KEY (`kinkompid`)
    REFERENCES `moviedb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviedb`.`seans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`seans` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filmid` INT(11) NOT NULL,
  `timestart` TIMESTAMP NULL DEFAULT NULL,
  `timeend` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seans_to_film_idx` (`filmid` ASC),
  CONSTRAINT `fk_seans_to_film`
    FOREIGN KEY (`filmid`)
    REFERENCES `moviedb`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moviedb`.`bron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviedb`.`bron` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bronstatus` VARCHAR(45) NULL DEFAULT NULL,
  `clientid` INT(11) NULL DEFAULT NULL,
  `seansid` INT(11) NULL DEFAULT NULL,
  `mestoid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_br_to_person_idx` (`clientid` ASC),
  INDEX `fk_br_to_seans_idx` (`seansid` ASC),
  INDEX `fk_br_to_mesto_idx` (`mestoid` ASC),
  CONSTRAINT `fk_br_to_mesto`
    FOREIGN KEY (`mestoid`)
    REFERENCES `moviedb`.`mesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_br_to_person`
    FOREIGN KEY (`clientid`)
    REFERENCES `moviedb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_br_to_seans`
    FOREIGN KEY (`seansid`)
    REFERENCES `moviedb`.`seans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
